webarena: true
max_timesteps: 10 # max number of timesteps for now; duplicate with verl-agent config.
common_webarena_host: "ec2-3-136-229-169.us-east-2.compute.amazonaws.com"
webarena_host:
      reddit: ${common_webarena_host} 
      shopping_admin: ${common_webarena_host}
      gitlab: ${common_webarena_host}
      map: ${common_webarena_host}
      shopping: ${common_webarena_host}

# for now we will use tti tasks for webarena
dataset:
  train_data_path: "$WEBARENA_DATA/webarena_test_data.jsonl" # for testing only "$WEBARENA_DATA/webarena_train_data.jsonl" 
  test_data_path: "$WEBARENA_DATA/webarena_test_data.jsonl"
